/**
 File: SearchScheduleByTaskName.js

 Date:      9/29/2025
 Author:    Jeffrey Whitney
            jtwhitney@machine.com
            651-319-7982

 Overview:
  - This page allows users to search for any part number and find out which production schedule(s) it's in 
    and which production machines are assigned to run that part.
  - The page is read-only and does not allow any data modification.
  - The data comes from data generated by the Schedule Refresh process that runs at 4:00 AM and 12:00 PM 
    every day. 
  - Wires up UI behavior for "Search Schedule/Machine Name by Task Name".
  - Manages pagination UI for a task results table based on a page index stored in `.pg input`.
  - Persists/restores site selection via cookie and normalizes the current user's network name.

 Key UI Contracts (expected DOM structure/selectors):
  - `.Submit` button (hidden on load).
  - `.lf-user-name input` contains a domain\user value; `.network-user-name input` receives normalized USERNAME.
  - `.pg input` holds the current page number (integer). Special value `999` = do not render pagination.
  - `.site-name input`, `.site-id input` are used to restore site from `site_name` cookie.
  - `.task-table` contains the results table; expects `.task-table table` and `.task-table tbody tr` rows.

 External Dependencies (loaded at runtime):
  - jQuery 1.7+ (assumed present).
  - jQuery Cookie (for reading the `site_name` cookie).
  - jQuery Confirm CSS/JS (styling and dialogs).
  - jQuery UI theme CSS.
  - simplePagination CSS (purely for styling the custom pagination markup created here).
  - Bootstrap (optional): `$.fn.button.noConflict()` is called; original plugin is re-alias'd to `$.fn.bootstrapBtn`.

 Events:
  - Listens for a custom `lookupcomplete` event on `document`. When fired, pagination is (re)built,
    page 999 is normalized to 1, site restored from cookie (if empty), and the task table is shown.

 Pagination Rules:
  - Page size is inferred as 25 rows. If exactly 25 rows are present, a "next" page is offered.
  - If fewer than 25 rows are present, "next" is disabled.
  - If current page > 1, "prev" and "first" controls are enabled.
  - If `.pg input` == 999, pagination is not rendered (reserved sentinel for "no paging" mode).

 Side Effects:
  - Replaces any existing `#user-pagination` before inserting a new one.
  - Hides `.task-table` during page changes to reduce flicker.
 */

$(document).ready(function () {
  // Hide submit buttons in this context; the page uses programmatic navigation.
  $('.Submit').hide();

  // Set document title for clarity.
  $(document).prop('title', 'Search Schedule/Machine Name by Task Name');

  // Load runtime dependencies (cookies, dialogs) and CSS themes.
  $.getScript('https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js');
  $.getScript('https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js');
  $("head").append('<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/smoothness/jquery-ui.css">');
  $("head").append('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/simplePagination.min.css">');
  $("head").append('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">');

  // Avoid Bootstrap/jQuery UI plugin conflicts; re-alias Bootstrap's button plugin.
  const bootstrapButton = $.fn.button.noConflict(); // return $.fn.button to previously assigned value
  $.fn.bootstrapBtn = bootstrapButton;

  // Normalize and populate the network username (strip domain, uppercase).
  const lfUserName = $('.lf-user-name input').val();
  if (lfUserName !== 'Anonymous User') {
    $('.network-user-name input').val(lfUserName.toUpperCase().substr(lfUserName.lastIndexOf('\\') + 1)).trigger("change");
  }

  // Handle post-lookup UI work: pagination, page normalization, cookie-based site restore, reveal table.
  $(document).on('lookupcomplete', function (e) {
    
    appendPagination();

    // If "no paging" sentinel (999) slipped through, normalize to page 1 for subsequent paging.
    if ($('.pg input').val() === '999') {
      $('.pg input').val(1).trigger("change");
    }

    // If site is not set, attempt to restore from cookie.
    if ($('.site-name input').val() === '') {
      const sitename = $.cookie('site_name');
      if (sitename !== null) {
        $('.site-name input').val(sitename).trigger("change");
        // Trigger a change on site id input to drive any dependent lookups.
        $('.site-id input').trigger("change");
      }
    }

    // Ensure the task table is visible after lookup completes.
    $('.task-table').show();
  });
});


/**
 * Builds and appends the pagination control beneath `.task-table table` based on:
 *  - current page from `.pg input`
 *  - current row count from `.task-table tbody tr`
 * When `.pg input` is 999 (sentinel), pagination is not rendered.
 *
 * Markup notes:
 *  - Inserts a container with id `user-pagination`.
 *  - Adds Prev (�, ��) and Next (�) anchors with enabled/disabled states and click handlers.
 *  - Removes an existing `#user-pagination` prior to rendering a new one.
 */
function appendPagination() {

  const current_page = Number($('.pg input').val());
  if (current_page === 999) { return; }

  const row_count = getTableRowCount();

  if (row_count > 0) {
    // Clear any previously injected pagination UI.
    $('#user-pagination').remove();

    // Case: first page and fewer than a full page of rows -> no next page.
    if ((current_page === 1) && (row_count < 25)) {
      $('.task-table table').parent().append("<div id='user-pagination' class='pagination light-theme simple-pagination'><ul><li><a class='page-link prev isDisabled'>��</a></li><li><a class='page-link prev isDisabled'>�</a></li><li><a class='page-link next isDisabled'>�</a></li></ul></div>");
      return;
    }

    // Case: first page and exactly a full page of rows -> next page enabled.
    if ((current_page === 1) && (row_count === 25)) {
      $('.task-table table').parent().append("<div id='user-pagination' class='pagination light-theme simple-pagination'><ul><li><a class='page-link prev isDisabled'>��</a></li><li><a class='page-link prev isDisabled'>�</a></li><li><a class='page-link next' onclick='callNextPage();' href='javascript:void(0);'>�</a></li></ul></div>")
      return;
    }

    // Case: middle pages and full page of rows -> next and prev enabled.
    if ((current_page > 1) && (row_count === 25)) {
      $('.task-table table').parent().append("<div id='user-pagination' class='pagination light-theme simple-pagination'><ul><li><a class='page-link prev' onclick='resetPageNumber();' href='javascript:void(0);''>��</a></li><li><a class='page-link prev' onclick='callPrevPage();' href='javascript:void(0);''>�</a></li><li><a class='page-link next' onclick='callNextPage();' href='javascript:void(0);'>�</a></li></ul></div>")
      return;
    }

    // Case: last page (fewer than a full page of rows) -> prev enabled, next disabled.
    if ((current_page > 1) && (row_count < 25)) {
      $('.task-table table').parent().append("<div id='user-pagination' class='pagination light-theme simple-pagination'><ul><li><a class='page-link prev' onclick='resetPageNumber();' href='javascript:void(0);''>��</a></li><li><a class='page-link prev' onclick='callPrevPage();' href='javascript:void(0);''>�</a></li><li><a class='page-link next isDisabled'>�</a></li></ul></div>")
      return;
    }
  }
}


/**
 * Advances to the next page:
 *  - Hides the task table (to reduce flicker) and increments `.pg input`, triggering its change handler.
 * Assumes an external listener reacts to `.pg input` changes to fetch/render new rows.
 */
function callNextPage() {
  $('.task-table').hide();

  current_page = Number($('.pg input').val());
  $('.pg input').val(current_page + 1).trigger("change");
}


/**
 * Navigates to the previous page (no-op if currently on page 1):
 *  - Hides the task table and decrements `.pg input`, triggering its change handler.
 */
function callPrevPage() {
  $('.task-table').hide();

  current_page = Number($('.pg input').val());
  if (current_page === 1) {
    return;
  }
  $('.pg input').val(current_page - 1).trigger("change");
}


/**
 * Navigates to the first page (page 1):
 *  - Hides the task table and resets `.pg input` to 1, triggering its change handler.
 */
function resetPageNumber() {
  $('.task-table').hide();
  $('.pg input').val(1).trigger("change");
}


/**
 * Gets the number of data rows currently rendered in the task table.
 * @returns {number} The count of `<tr>` elements within `.task-table tbody`.
 */
function getTableRowCount() {
  const row_count = $('.task-table tbody tr').length;
  return row_count;
}